name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: setup node ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install yarn
        run: yarn install
        working-directory: html-report/ui

      - name: Build
        run: yarn build
        working-directory: html-report/ui

      - name: Test
        run: yarn test
        working-directory: html-report/ui
